mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:com/fzu/CloudClass/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.fzu.CloudClass.common.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    #db-column-underline: true
    #刷新mapper 调试神器
    #refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    # Sequence序列接口实现类配置
    #key-generator: com.baomidou.mybatisplus.incrementer.OracleKeyGenerator
    #逻辑删除配置（下面3个配置）
    #logic-delete-value: 1
    #logic-not-delete-value: 0
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #配置JdbcTypeForNull
    jdbc-type-for-null: 'null'
spring:
  application:
    name: ${SPRING_APPLICATION_NAME:CloudClass}
#    redis:
#      host: ${REDIS_HOST:192.168.99.100}
#      port: 6379
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.140.0.237:3306/cloudclass?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: cloudclass123456
server:
  servlet:
    context-path: /api
  port: 8080
opentracing:
  jaeger:
    http-sender:
      url: http://${JAEGER_ENDPOINT:localhost}:14268/api/traces
jwt:
  # 加密密钥
  secret: cloudclass1234567
  # token有效时长
  expire: 36000
  # header 名称
  header: token

#oauth:
#  github:
#    app-id: 1ce1ed69349a9f307417
#    app-secret: 1909c97b4b153eb5273f5086e5a11ddedd7e79d9
#
oauth:
  github:
    app-id: 1bcc057d1fa210ff880a
    app-secret: 0282c18668f9495cc7b64c4685c241b7caae062b